/* 
 * File:   mcal_internal_interrupt.h
 * Author: minas
 *
 * Created on September 5, 2023, 8:34 AM
 */

#ifndef MCAL_INTERNAL_INTERRUPT_H
#define	MCAL_INTERNAL_INTERRUPT_H

/* Section :  Includes   */
#include "mcal_interrupt_cfg.h"
/* Section :  Macro declaration   */



/* Section :  Macro function   */
#if ADC_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
   /*THIS MACRO ENABLE/DISABLE INTERRUPT FOR INTERUPT ADC */
#define ADC_INTERRUPT_DISABLE()          (PIE1bits.ADIE = 0)
#define ADC_INTERRUPT_ENABLE()           (PIE1bits.ADIE = 1)
/*THIS MACRO CLEAR FLAG  OF  INTERUPT ADC */
#define ADC_INTERRUPT_FLAG_CLEAR()       (PIR1bits.ADIF = 0)
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define ADC_HIGH_PRIORITY_SET()        (IPR1bits.ADIP = 1)
#define ADC_LOW_PRIORITY_SET()         (IPR1bits.ADIP = 0)
#endif
#endif

#if TIMER0_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
   /*THIS MACRO ENABLE/DISABLE INTERRUPT FOR INTERUPT TIMER0 */
#define TIMER0_INTERRUPT_DISABLE()          (INTCONbits.TMR0IE = 0)
#define TIMER0_INTERRUPT_ENABLE()           (INTCONbits.TMR0IE = 1)
/*THIS MACRO CLEAR FLAG  OF  INTERUPT TIMER0 */
#define TIMER0_INTERRUPT_FLAG_CLEAR()       (INTCONbits.TMR0IF = 0)
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER0_HIGH_PRIORITY_SET()        (INTCON2bits.TMR0IP = 1)
#define TIMER0_LOW_PRIORITY_SET()         (INTCON2bits.TMR0IP = 0)
#endif
#endif


#if TIMER1_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
   /*THIS MACRO ENABLE/DISABLE INTERRUPT FOR INTERUPT TIMER1 */
#define TIMER1_INTERRUPT_DISABLE()          (PIE1bits.TMR1IE = 0)
#define TIMER1_INTERRUPT_ENABLE()           (PIE1bits.TMR1IE = 1)
/*THIS MACRO CLEAR FLAG  OF  INTERUPT TIMER1 */
#define TIMER1_INTERRUPT_FLAG_CLEAR()       (PIR1bits.TMR1IF = 0)
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER1_HIGH_PRIORITY_SET()        (IPR1bits.TMR1IP = 1)
#define TIMER1_LOW_PRIORITY_SET()         (IPR1bits.TMR1IP = 0)
#endif
#endif

#if TIMER2_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
   /*THIS MACRO ENABLE/DISABLE INTERRUPT FOR INTERUPT TIMER2 */
#define TIMER2_INTERRUPT_DISABLE()          (PIE1bits.TMR2IE = 0)
#define TIMER2_INTERRUPT_ENABLE()           (PIE1bits.TMR2IE = 1)
/*THIS MACRO CLEAR FLAG  OF  INTERUPT TIMER2 */
#define TIMER2_INTERRUPT_FLAG_CLEAR()       (PIR1bits.TMR2IF = 0)
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER2_HIGH_PRIORITY_SET()        (IPR1bits.TMR2IP = 1)
#define TIMER2_LOW_PRIORITY_SET()         (IPR1bits.TMR2IP = 0)
#endif
#endif

#if TIMER3_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
/*THIS MACRO ENABLE/DISABLE INTERRUPT FOR INTERUPT TIMER3 */
#define TIMER3_INTERRUPT_DISABLE()          (PIE2bits.TMR3IE = 0)
#define TIMER3_INTERRUPT_ENABLE()           (PIE2bits.TMR3IE = 1)
/*THIS MACRO CLEAR FLAG  OF  INTERUPT TIMER3 */
#define TIMER3_INTERRUPT_FLAG_CLEAR()       (PIR2bits.TMR3IF = 0)
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define TIMER3_HIGH_PRIORITY_SET()        (IPR2bits.TMR3IP = 1)
#define TIMER3_LOW_PRIORITY_SET()         (IPR2bits.TMR3IP = 0)
#endif
#endif

#if CCP1_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
/*THIS MACRO ENABLE/DISABLE INTERRUPT FOR INTERUPT CCP1 */
#define CCP1_INTERRUPT_DISABLE()          (PIE1bits.CCP1IE = 0)
#define CCP1_INTERRUPT_ENABLE()           (PIE1bits.CCP1IE = 1)
/*THIS MACRO CLEAR FLAG  OF  INTERUPT CCP1 */
#define CCP1_INTERRUPT_FLAG_CLEAR()       (PIR1bits.CCP1IF = 0)
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define CCP1_HIGH_PRIORITY_SET()        (IPR1bits.CCP1IP = 1)
#define CCP1_LOW_PRIORITY_SET()         (IPR1bits.CCP1IP = 0)
#endif
#endif

#if CCP2_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
/*THIS MACRO ENABLE/DISABLE INTERRUPT FOR INTERUPT CCP2 */
#define CCP2_INTERRUPT_DISABLE()          (PIE2bits.CCP2IE = 0)
#define CCP2_INTERRUPT_ENABLE()           (PIE2bits.CCP2IE = 1)
/*THIS MACRO CLEAR FLAG  OF  INTERUPT CCP2 */
#define CCP2_INTERRUPT_FLAG_CLEAR()       (PIR2bits.CCP2IF = 0)
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define CCP2_HIGH_PRIORITY_SET()        (IPR2bits.CCP2IP = 1)
#define CCP2_LOW_PRIORITY_SET()         (IPR2bits.CCP2IP = 0)
#endif
#endif

#if ESUART_TX_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
/*THIS MACRO ENABLE/DISABLE INTERRUPT FOR INTERUPT ESUART_TX */
#define ESUART_TX_INTERRUPT_DISABLE()          (PIE1bits.TXIE = 0)
#define ESUART_TX_INTERRUPT_ENABLE()           (PIE1bits.TXIE = 1)
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define ESUART_TX_HIGH_PRIORITY_SET()        (IPR1bits.TXIP = 1)
#define ESUART_TX_LOW_PRIORITY_SET()         (IPR1bits.TXIP = 0)
#endif
#endif

#if ESUART_RX_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
/*THIS MACRO ENABLE/DISABLE INTERRUPT FOR INTERUPT ESUART_RX */
#define ESUART_RX_INTERRUPT_DISABLE()          (PIE1bits.RCIE = 0)
#define ESUART_RX_INTERRUPT_ENABLE()           (PIE1bits.RCIE = 1)
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define ESUART_RX_HIGH_PRIORITY_SET()          (IPR1bits.RCIP = 1)
#define ESUART_RX_LOW_PRIORITY_SET()           (IPR1bits.RCIP = 0)
#endif 
#endif


#if MSSP_I2C_INTERRUPT_FEATURE_ENABLE == INTERRUPT_FEATURE_ENABLE
/*THIS MACRO ENABLE/DISABLE INTERRUPT FOR INTERUPT MSSP_I2C */
#define MSSP_I2C_INTERRUPT_DISABLE()                  (PIE1bits.SSPIE = 0)
#define MSSP_I2C_INTERRUPT_ENABLE()                   (PIE1bits.SSPIE = 1)
#define MSSP_I2C_BUS_COL_INTERRUPT_DISABLE()          (PIE2bits.BCLIE = 0)
#define MSSP_I2C_BUS_COL_INTERRUPT_ENABLE()           (PIE2bits.BCLIE = 1)
/*THIS MACRO CLEAR FLAG  OF  INTERUPT MSSP_I2C */
#define MSSP_I2C_INTERRUPT_FLAG_CLEAR()               (PIR1bits.SSPIF = 0)
#define MSSP_I2C_BUS_COL_INTERRUPT_FLAG_CLEAR()       (PIR2bits.BCLIF = 0)
#if INTERRUPT_PRIORITY_LEVELS_ENABLE == INTERRUPT_FEATURE_ENABLE
#define MSSP_I2C_HIGH_PRIORITY_SET()                (IPR1bits.SSPIP = 1)
#define MSSP_I2C_LOW_PRIORITY_SET()                 (IPR1bits.SSPIP = 0)
#define MSSP_I2C_BUS_COL_HIGH_PRIORITY_SET()        (IPR2bits.BCLIP = 1)
#define MSSP_I2C_BUS_COL_LOW_PRIORITY_SET()         (IPR2bits.BCLIP = 0)
#endif
#endif
/* Section :  Data types   */


/* Section :  Function Declaration   */

void ADC_ISR(void);
void Timer0_ISR (void);
void Timer1_ISR (void);
void Timer2_ISR (void);
void Timer3_ISR (void);
void CCP1_ISR (void);
void CCP2_ISR (void);
void EUSART_TX_ISR (void);
void EUSART_RX_ISR (void);
void MSSP_I2C_ISR (void);
void MSSP_I2C_BCL_ISR (void);

#endif	/* MCAL_INTERNAL_INTERRUPT_H */

